### ISSUE TITLE
Test compiling some coffeescript

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/coffeescript-feedstock#1]
Would be nice if this test compiling a "Hello World" like program with coffeescript. Just to make sure it is behaving as intended.

**Comment by sannykr** [comment]
@jakirkham : Thanks. I will add that in the test section.

**Comment by jakirkham** [comment]
Thanks @sannykr. Also, as a friendly reminder, please make sure to make the changes on your fork of the feedstock and then PR them. :)
